#!/usr/bin/env bash
source ./settings/project.config.sh

# 
# summary
# 
#     this file is used to run commands
#     it loads the PROJECTR env variables first (./settings/project.config.sh)
#     then in looks inside the commands folder for commands to run
#     (unlike the underscore, this does not load the manual environment)

# 
# no args
# 
if [[ "$#" = "0" ]]
then
    # start the shell
    "$PROJECTR_COMMANDS_FOLDER/shell"
# 
# otherwise run the respective project command
# 
else
    absolute_path () {
        echo "$(builtin cd "$(dirname "$1")"; pwd)/$(basename "$1")"
    }
    # 
    # recursively drill down
    # 
    search_path="$PROJECTR_COMMANDS_FOLDER"
    argument_combination="$search_path/$1"
    while [[ -n "$@" ]]
    do
        # pop the first argument off
        shift 1
        for each in $(find "$search_path" -maxdepth 1 ! -path .)
        do
            if [[ "$(absolute_path "$argument_combination")" = "$(absolute_path "$each")" ]]
            then
                # if its a folder, then we need to go deeper
                if [[ -d "$each" ]]
                then
                    search_path="$each"
                    argument_combination="$argument_combination/$1"
                    
                    # if there is no next argument
                    if [[ -z "$1" ]]
                    then
                        printf "\nThat is a sub folder, not a command\nValid sub-options are\n" 1>&2
                        ls -1 --color -F "$each" | sed 's/^/    /' 1>&2
                        exit 1 # error, no command
                    fi
                    
                    break
                # if its a file, run it with the remaining arguments
                elif [[ -f "$each" ]]
                then
                    "$each" "$@"
                    # make exit status identical to executed program
                    exit $?
                fi
            fi
        done
    done
    printf "\nI could not find that command\n" 1>&2
    printf "Valid options are:\n" 1>&2
    ls -1 "$search_path" | sed 's/^/    /' 1>&2
    exit 1 # error, no command
fi