#!/usr/bin/env bash
echo "project commands:"
ls -1 --color ./settings/commands | sed 's/^/    /'
# print the node commands
node -e 'try { Object.keys(require("./package.json").scripts).forEach(each=>console.log(`    npm run ${each}`))}catch(e){}'  