#!/usr/bin/env bash
gc python            && gm master      && gp && \
gc python_package    && gm python      && gp && \
gc python_notebook   && gm python      && gp && \
gc node              && gm python      && gp && \
gc quik_github_pages && gm node        && gp && \
gc npm_package       && gm node        && gp && \
gc vs_code_extension && gm npm_package && gp && \
gc deno_package      && gm master      && gp && \
gc pnpm              && gm node        && gp && \
gc electron          && gm node        && gp && \
gc prolog            && gm master      && gp && \
gc ruby              && gm master      && gp && \
gc rust              && gm master      && gp && \
gc rust_druid        && gm rust        && gp && \
gc rust_tauri        && gm rust        && gp && \
gc textmate          && gm npm_package && gp && \
gc textmate          && gm ruby        && gp && \
gc crystal           && gm master      && gp && \
gc master