#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups

# python cache at any level (half second to rebuild these)
rm -rf **/__pycache__

# all the virtual env pip modules (several minutes to rebuild these)
rm -rf .venv

# misc
rm -rf ./settings/.cache
rm -f .project_dir.nosync.txt