#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups

# the usual things
rm -rfv ./settings/.cache **/*.cleanable **/*.cleanable.*