#!/usr/bin/env bash
echo "
========================================================================
  Help (press q to exit, scroll with mouse or arrow keys)
========================================================================

This command should explain the structure of the project
    - how to find the source code of some feature 
    - what to expect when running tests
    - resolving common errors
    - metion API/documentation
    - references to readme and other files
    - etc

" | less