#!/usr/bin/env bash

# 
# establish PROJECTR variables
# 
if [ -z "$PROJECTR_FOLDER" ]
then
    # 
    # find projectr_core
    # 
    path_to_file=""
    file_name="settings/projectr_core"
    folder_to_look_in="$PWD"
    while :
    do
        # check if file exists
        if [ -f "$folder_to_look_in/$file_name" ]
        then
            path_to_file="$folder_to_look_in/$file_name"
            break
        else
            if [ "$folder_to_look_in" = "/" ]
            then
                break
            else
                folder_to_look_in="$(dirname "$folder_to_look_in")"
            fi
        fi
    done
    if [ -z "$path_to_file" ]
    then
        #
        # what to do if file never found
        #
        echo "Im a script running with a pwd of:$PWD"
        echo "Im looking for settings/projectr_core in a parent folder"
        echo "Im exiting now because I wasnt able to find it"
        echo "thats all the information I have"
        exit
    fi
    export PROJECTR_NEXT_RUN_ONLY_DO_BASIC_INIT="true"
    # run the basic init of projectr to get the PROJECTR_FOLDER/PROJECTR_COMMANDS_FOLDER/PROJECTR_HOME etc
    source "$path_to_file"
fi

# 
# 
# run manual_setup
# 
#
source "$PROJECTR_COMMANDS_FOLDER/tools/manual_setup"