#!/usr/bin/env bash

# summary
#     this just removes all of the can-be deleted files
#     can be useful for fixing corrupted setups

# if you want to add something
#     edit the settings/during_clean/ 
#     (add your own file to that folder like 001_clean_mything.sh)

# source all the file in settings/during_clean/ in alphabetical order
. "$FORNIX_FOLDER/settings/extensions/#standard/commands/tools/fornix/trigger" "$FORNIX_FOLDER/settings/during_clean"