#!/usr/bin/env bash

root="$FORNIX_FOLDER"
if [ -z "$root" ]
then
    root="$PWD"
fi

npm version patch \
    && "$root/commands/project/build" \
    && npm publish --access=public --no-git-checks \
    && git push &>/dev/null \
    && git add -A \
    && git commit -m 'build and version bump' \
    && git push