#!/usr/bin/env bash

vsce publish --pat "$1" && echo "published on VSCE"
ovsx publish -p "$2" && echo "published on OVSX"

tag_name="$(jq '.version' ./package.json)"
git tag "$tag_name" && git push origin "$tag_name"