#!/usr/bin/env bash

# summary
#   this is a nuclear cleaning option 
#   - if its not part of the git repo
#   - and it will take a long time (>1min) to get the data back
#   => this command should get rid of it
#   useful when you're trying to reset a project back to 0 when debugging

read -p "Are you sure? (y/n)" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "canceling"
    exit 0
fi

del () {
    if [ -f "$1" ]
    then
        rm -fv "$1"
    else
        rm -rfv "$1"
    fi
}

# clean all the small things
"$PROJECTR_COMMANDS_FOLDER/project/clean"

# the mac library cache
if [[ -d "$PROJECTR_FOLDER" ]]
then
    del "$PROJECTR_HOME/Library/Caches"
fi

# delete venv
del "$PROJECTR_FOLDER/.venv"
