#!/usr/bin/env bash

npx textmate-tester \
    --textmateExtension YOUR_LANG_EXTENSION_HERE \
    --syntax "$FORNIX_FOLDER/syntaxes/YOUR_LANG_EXTENSION_HERE.tmLanguage.json" \
    --examples "$FORNIX_FOLDER/examples/" \
    generate-specs --all