#!/usr/bin/env bash

# if PROJECTR_FOLDER is not set, then assume the current folder
if [[ -z "$PROJECTR_FOLDER" ]]
then
    PROJECTR_FOLDER="$PWD"
fi

# main inputs
name_of_check="pip modules"
file_to_watch="requirements.txt"
hash_check_name="pip_modules"
function failed_check_command {
    # what to do when pip modules haven't been installed yet
    # only save the hash if the install is successful
    python -m pip --disable-pip-version-check install -r "$file_to_watch"
}
function generate_file_command {
    # what to do when requirements file doesn't exist
    python -m pip freeze > "$file_to_watch"
}

echo "Running $name_of_check check"

# ensure that the source file and hash file exist
if ! [[ -f "./$file_to_watch" ]]; then
    generate_file_command
fi
location_of_hash="$PROJECTR_FOLDER/settings/.cache/.$hash_check_name.cleanable.hash"
if ! [[ -f "$location_of_hash" ]]; then
    # make sure the folder exists
    mkdir -p "$(dirname "$location_of_hash")"
    touch "$location_of_hash"
fi

# check if need to do install using that hash
old_hash="$(cat "$location_of_hash")"
new_hash="$(cat "$file_to_watch" | md5sum)"
if [[ "$old_hash" != "$new_hash" ]]; then
    failed_check_command && echo "$new_hash" > "$location_of_hash"
else
    echo "I see a cached $name_of_check check => assuming packages are installed"
fi