#!/usr/bin/env bash
function escape_sed_regex() {
    sed 's/[][\.|$(){}?+*^]/\\&/g' <<< "$*" | sed 's|/|\\/|g'
}

if [ -f "$1" ]
then
    rm -fv "$1" | sed 's/^removed '"'$(escape_sed_regex "$PROJECTR_FOLDER")"'/removed ./'
else
    rm -rfv "$1" | sed 's/^removed '"'$(escape_sed_regex "$PROJECTR_FOLDER")"'/removed ./'
fi