#!/usr/bin/env -S deno run --allow-all
const { run, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo, zipInto, mergeInto, returnAsString, } = await import(`https://deno.land/x/quickr@0.3.20/main/run.js`)
const { FileSystem } = await import(`https://deno.land/x/quickr@0.3.20/main/file_system.js`)

// 
// args
// 
let [ fileOrFolderPath ] = Deno.args

// 
// run
// 
await FileSystem.addPermissions({
    path: fileOrFolderPath,
    recursively: true,
    permissions: {
        owner: {
            canExecute: true,
        },
    }
})