#!/usr/bin/env -S deno run --allow-all
const { run, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo, zipInto, mergeInto, returnAsString, } = await import(`https://deno.land/x/sprinter@0.3.2/index.js`)
const { FileSystem, Console } = await import(`https://deno.land/x/file_system_js@0.0.16/main/deno.js`)

// 
// args
// 
let [ fileOrFolderPath ] = Deno.args

// 
// run
// 
await FileSystem.addPermissions({
    path: fileOrFolderPath,
    recursively: true,
    permissions: {
        owner: {
            canExecute: true,
        },
    }
})